### PR TITLE
docs: add info about using

### PR DESCRIPTION
**Pull request by istudyatuni**

### CODE REVIEW

**Comment by istudyatuni** [comment]
I would also suggest doing a squash merge instead of default to keep history more linear

**Comment by istudyatuni** [comment]
@eliaperantoni this PR is ready

**Comment by eliaperantoni** [comment]
I know, I'm just a little busy lately. I want to make sure I properly review it before I accept it.

**Comment by istudyatuni** [comment]
Oh, okay, sorry

**Pull request merged**
